---
name: Gem Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Release gem
    runs-on: ubuntu-latest
    environment: release

    permissions:
      id-token: write

    steps:
      - uses: ekohl/ruby-release@v0
