name: Gem Release

on:
  create:
    ref_type: tag

jobs:
  release:
    name: Release gem
    permissions:
      contents: write
      id-token: write
    uses: ekohl/actions/.github/workflows/release-gem.yml@trusted-publishing
    with:
      allowed_owner: voxpupuli
