name: Gem Release

on:
  create:
    ref_type: tag

jobs:
  release:
    name: Release gem
      uses: ekohl/actions/.github/workflows/release-gem@v0
      with:
        allowed_owner: voxpupuli
      secrets:
        api_key: ${{ secrets.RUBYGEMS_AUTH_TOKEN }}
